name: Deploy to Elastic Beanstalk

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --production

      - name: Create ZIP package
        run: zip -r app.zip . -x "*.git*" "node_modules/*"

      - name: Check if secrets exist
        run: |
          if [ -z "${{ secrets.AWS_ACCESS_KEY_ID }}" ]; then
            echo "AWS_ACCESS_KEY_ID is EMPTY ❌"
            exit 1
          else
            echo "AWS_ACCESS_KEY_ID is set ✅"
          fi

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          application_name: MySampleApp          # EXACT EB app name
          environment_name: MySampleApp-env      # EXACT EB env name
          version_label: v-${{ github.run_number }}
          region: us-east-1
          deployment_package: app.zip
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
